Add serialize bilibili json component.
vNerve/vNerveBiLiveReceptor pull request #1
Opened 2020-04-30 13:24 UTC by H4M5TER

2020-04-30 13:32 UTC, cqjjjzr requested changes

2020-04-30 13:32 UTC, cqjjjzr commented on CMakeLists.txt
> +conan_cmake_run(REQUIRES
与当前分支冲突，Merge时注意删掉这一段

2020-04-30 13:32 UTC, cqjjjzr commented on src/worker/borrowed_buffer.h
> +class borrowed_buffer
建议把这一段移到json里面
并且我觉得可以specialize一下，改名为例如`borrowed_message`，因为后面还可能往里面加入routing key的代码

2020-04-30 13:32 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +robin_hood::unordered_map<string, function<void(const Document&, RoomMessage*, Arena*)>> command;
map哪来的初始化容量¿

2020-04-30 13:32 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    auto const& info_iter = document["info"].Begin();
这里为何是iterator而非数组本身

2020-04-30 13:32 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    if ((user_info_iter + 3)->GetBool() == (user_info_iter + 4)->GetBool())
这里不太清晰 建议写成
```
if (!3 && !4) 无
else if (!3 && 4) 年费
else if (3 && !4) 月费
else error
```

2020-04-30 13:32 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +        user_info->set_regular_user(false);
建议单行酌情加花括号

2020-04-30 13:43 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +        user_info->set_regular_user(false);
这里主要是错误处理还没写 前面那些写完的我都统一整改了
顺便一提 不知道为什么 前面写完的用ASSERT_TRACE 最后明明是else却不缩进 非要大括号 但是大括号又太刷kpi了 所以就同一个缩进了 你有什么解决方案吗

2020-04-30 13:48 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    auto const& info_iter = document["info"].Begin();
说实话我并不是很懂rapidjson的最佳实践 譬如document["info"]和document["info].GetArray()有什么区别?
另外iterator我觉得也是可以接受的 毕竟数组里同一个位置的数据需要复用若干次 如果能每次手动++iter就感觉不错 就是不知道存一个iter会不会有内存碎片了

2020-04-30 13:51 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +robin_hood::unordered_map<string, function<void(const Document&, RoomMessage*, Arena*)>> command;
所以我一开始打算直接把函数写在map的初始化里 希望能确保固定的内存分配 但是后来忘记因为什么转到宏去了 不过这个注释还留着

2020-04-30 13:56 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    auto const& info_iter = document["info"].Begin();
你可以存指向Array的引用，另外或许你不应该把iter保存成引用..

2020-04-30 13:57 UTC, H4M5TER commented on src/worker/borrowed_buffer.h
> +class borrowed_buffer
目前bili_json.cpp里已经有一个borrowed_message继承borrowed_buffer了 这种做法不就是你当初想要的虚函数调用吗
至于borrowed_message需不需要整个对外公开 视后面计划的调用形式而定
我目前感觉依然可以包装起来 即使未来有写入除protobuf外的东西的需求

2020-04-30 13:57 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +        user_info->set_regular_user(false);
我觉得你ASSERT_TRACE有点问题
我觉得应该写成
```cpp
#define ASSERT_TRACE(expr) \
if (!(expr)) {
// LOG ERROR
return nullptr; // 或同等类型
}
```

2020-04-30 13:58 UTC, H4M5TER commented on CMakeLists.txt
> +conan_cmake_run(REQUIRES
为什么这块你要写下面

2020-04-30 17:57 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +        user_info->set_regular_user(false);
类型检查已经重构

2020-04-30 17:57 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    if ((user_info_iter + 3)->GetBool() == (user_info_iter + 4)->GetBool())
在每一处添加了备注

2020-04-30 17:58 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    auto const& info_iter = document["info"].Begin();
尝试性地重构了一下

2020-05-01 02:49 UTC, cqjjjzr requested changes

2020-05-01 02:49 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    // 或许应改成document["info"].MemberCount() >= 15
的确如此

2020-05-01 02:49 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    embeded_user_info->set_uid(user_info[0].GetUint64());
typo: embedded

2020-05-01 10:10 UTC, H4M5TER commented on src/worker/borrowed_buffer.h
> +class borrowed_buffer
目前的需求: 在外界调用serialize获得borrowed_buffer 将负载和routingkey一并写入外界的存储 通过负载计算CRC32
目前的实现: 在外界通过borrowed_buffer的虚函数表将"一块内存"写入外界的存储

需要补充校验码相关的实现

2020-05-01 10:21 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +robin_hood::unordered_map<string, function<void(const Document&, RoomMessage*, Arena*)>> command;
经过讨论: 介于command是只对本cpp文件内可访问的 所以放弃const以使用emplace_back是可以接受的

2020-05-01 10:29 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    auto const& info_iter = document["info"].Begin();
经过讨论 GenericArray::operator[]是和使用iterator开销相近的 可以直接切换使用

2020-05-07 14:25 UTC, cqjjjzr requested changes

2020-05-07 14:25 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +const borrowed_buffer* serialize_buffer(char* buf, const unsigned int& room_id)
这里为什么是 `int&`

2020-05-07 14:25 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    // 弹幕没有牌子属于的用户的uid的字段
牌子属于的用户的Uid指的是主播UID？那可能确实无

2020-05-07 14:25 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    // 以下变量均为 rapidjson::GenericArray ?
难道不是`GenericObject`?

2020-05-07 14:25 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    ASSERT_TRACE(data.HasMember("uid"))
强烈建议使用 `FindMember` 函数避免多次寻找。应通过判断 `iterator` 与 `MemberEnd` 确定存在性

2020-05-07 14:25 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    embedded_user_info->set_regular_user(true);
建议未来将 `regular_user` 这几个字段用 `oneof` 保存（oneof 有微小的开销

2020-05-07 14:25 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    // 没有对应的字段
暂时不需要

2020-05-07 14:25 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    // 礼物似乎没有牌子信息
默认 `null` 即可

2020-05-07 14:48 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    // 弹幕没有牌子属于的用户的uid的字段
SC有 targetid就是

2020-05-07 14:49 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    // 以下变量均为 rapidjson::GenericArray ?
复制错了

2020-05-07 14:50 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +const borrowed_buffer* serialize_buffer(char* buf, const unsigned int& room_id)
传入不会更改的参数不就应该是const&吗

2020-05-07 14:50 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    ASSERT_TRACE(data.HasMember("uid"))
请详述“多次寻找”

2020-05-07 14:51 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    embedded_user_info->set_regular_user(true);
可选字段都应改为用oneof保存 transmitter更改还未commit

2020-05-07 14:52 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    // 没有对应的字段
需要根据下游需求决定

2020-05-07 14:52 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    // 礼物似乎没有牌子信息
直接不set_allocated_medal不可以吗

2020-05-07 15:00 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    // 礼物似乎没有牌子信息
可以

2020-05-07 15:02 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    ASSERT_TRACE(data.HasMember("uid"))
`GenericObject` 内部类似于 `unordered_map<string, GenericValue>`。这段代码会三次利用键寻找值。而改为 `FindObject` 仅会发生一次。

2020-05-07 15:02 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +const borrowed_buffer* serialize_buffer(char* buf, const unsigned int& room_id)
`int` 等基础类型不需要。直接复制的开销甚至可能小于复制一个64位指针。

2020-05-07 15:03 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    // 弹幕没有牌子属于的用户的uid的字段
那可能需要oneof

2020-05-07 15:05 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    ASSERT_TRACE(data.HasMember("uid"))
能不能科普一下为什么会三次查询

2020-05-07 15:05 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    ASSERT_TRACE(data.HasMember("uid"))
另外MemberEnd是开销极小是吗

2020-05-07 15:06 UTC, cqjjjzr commented on src/worker/bili_json.cpp
> +    ASSERT_TRACE(data.HasMember("uid"))
分别为 `HasMember` 调用和两次 `operator[]` 调用，产生三次查询。  
可以理解为内联后几乎无开销。

2020-05-07 15:07 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +const borrowed_buffer* serialize_buffer(char* buf, const unsigned int& room_id)
了解

2020-05-07 15:12 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    // 弹幕没有牌子属于的用户的uid的字段
同下下

2020-05-07 15:14 UTC, H4M5TER commented on src/worker/bili_json.cpp
> +    ASSERT_TRACE(data.HasMember("uid"))
了解

2020-05-31 06:16 UTC, cqjjjzr commented on src/worker/borrowed_buffer.h
> +class borrowed_buffer
CRC32的计算建议使用原JSON数据，在`ParseInsitu`之前计算

2020-05-31 06:16 UTC, cqjjjzr commented
参见 vNerve/vNerveTransmitter#2

2020-06-07 09:12 UTC, merged